name: test by python unittest framework 
on:
    workflow_dispatch:
    push:
        paths-ignore:
            - 'README.md'
            - '**.yml'
jobs:
    test_job:
        runs-on: ubuntu-latest
        env:
            var2: ${{ vars.var2 }}
            var3: ${{ secrets.var3 }}
        steps:
            - name: 저장소 체크아웃
              uses: actions/checkout@v4

            - name: 파이썬 셋업
              uses: actions/setup-python@v5
              with:
                python-version: '3.9'
            
            - name: 실행
              run: |
                python tests.py